Cap_Ele
Cap_Ele_Bio
Cap_Ele_Bio_w_CCS
Cap_Ele_Bio_wo_CCS
Cap_Ele_Coa
Cap_Ele_Coa_w_CCS
Cap_Ele_Coa_wo_CCS
Cap_Ele_Gas
Cap_Ele_Gas_w_CCS
Cap_Ele_Gas_wo_CCS
Cap_Ele_Geo
Cap_Ele_Hyd
Cap_Ele_Nuc
Cap_Ele_Oil
Cap_Ele_Oil_w_CCS
Cap_Ele_Oil_wo_CCS
Cap_Ele_Solar
Cap_Ele_SolarCSP
Cap_Ele_SolarPV
Cap_Ele_Win
Cap_Ele_Win_Off
Cap_Ele_Win_Ons
Cap_Ele_Oth
* Cap_Ele_Pea_Dem
Cap_Ele_Sto
Cap_Ele_Sto_Cap
* Cap_Ele_Tra_Gri
Cap_Hyd_Ele
